# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-29 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ggwp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sulg',
            new_name='slug',
        ),
    ]
