# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-04-04 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ggwp', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='piture',
            new_name='picture',
        ),
    ]
